# Generated by Django 3.2.8 on 2021-10-25 17:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, size=None)),
                ('published_date', models.DateField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, size=None)),
                ('average_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ratings_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('thumbnail', models.URLField(blank=True)),
            ],
        ),
    ]
