# Generated by Django 3.2.8 on 2021-10-25 20:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None),
        ),
    ]
